spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://32.193.203.94:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**
        - id: location-service
          uri: http://location-service:8082
          predicates:
            - Path=/locations, /locations/**
          filters:
            - AuthenticationFilter
        - id: review-service
          uri: http://review-service:8083
          predicates:
            - Path=/reviews, /reviews/**
          filters:
            - AuthenticationFilter

server:
  port: 8080