# Identificação do Serviço
spring.application.name=auth-service
server.port=8081

# Conexão com o PostgreSQL (usando o nome do serviço definido no Docker)
spring.datasource.url=jdbc:postgresql://postgres:5432/incluicity_db
spring.datasource.username=admin
spring.datasource.password=admin123

# Hibernate - Cria as tabelas automaticamente baseado no seu Usuario.java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.api-docs.path=/auth/v3/api-docs
springdoc.swagger-ui.path=/auth/swagger-ui.html